apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-ingredientes
spec:
  selector:
    matchLabels:
      app: api-ingredientes
  replicas: 1
  template:
    metadata:
      labels:
        app: api-ingredientes
    spec:
      containers:
        - name: api-ingredientes
          image: humbertosandmann/account:latest
          ports:
            - containerPort: 8080
          env:

            - name: DISCOVERY_HOST
              valueFrom:
                configMapKeyRef:
                  name: discovery-configmap
                  key: DISCOVERY_HOST

            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_HOST

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB

            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USERNAME

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD