apiVersion: v1
kind: Service
metadata:
  name: ingredientes
  labels:
    name: ingredientes
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: ingredientes