apiVersion: v1
kind: Service
metadata:
  name: api-ingredientes
  labels:
    name: api-ingredientes
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: api-ingredientes